### PR TITLE
WIP: useFormless should be the default export

### PR DESCRIPTION
**Pull request by alexismellamo**
Change useFormless to be the default export

### CODE REVIEW

**Comment by alexismellamo** [comment]
First let's discuss this, then I can finish this (we need to change the read me and codesandbox)

**Comment by GeDiez** [comment]
i think this is a best approach using `default export` too.
i will add this change, and then i will launch the version 1

**Comment by GeDiez** [comment]
@alexisllamas can you update the README file?

**Comment by GeDiez** [comment]
change added at version 0.1.0

**Pull request closed without merging**
